# .github/workflows/pipeline-branch-name.yml
name: Pipeline — branch-name

on:
  pull_request:
    types: [opened, synchronize, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  branch-name:
    uses: leebaroneau/pipeline-core/.github/workflows/branch-name.yml@v1
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    with:
      config-path: .github/pipeline-config.yml
